import { createHash, createSign, createVerify, type KeyLike } from "node:crypto";
import { err, ok, type Result } from "@nova/shared";
import { PLUGIN_PERMISSION_SCOPES, type PluginManifest, type PluginPermissionScope } from "./plugin-manager.js";
import { createTarGz, type ArchiveEntry } from "./archive.js";

/**
 * `nova plugin create` / `validate` / `sign` / `package` per
 * docs/27-cli/06-plugin-and-ai-sdk.md. `publish` is still deliberately
 * not implemented: it requires a marketplace registry endpoint
 * (`docs/16-extensibility/plugin-marketplace.md`) that doesn't exist
 * anywhere in this repo — a real integration decision, not something to
 * guess at. `package` was in the same boat until this pass chose
 * tar.gz/USTAR as the archive format (see `archive.ts`'s top comment
 * for why) — `packagePlugin` below runs `validatePluginManifest` as its
 * first step, per this doc's note that validation is a mandatory
 * pre-step for both `package` and `publish`.
 */

export interface PluginScaffold {
  readonly manifestJson: string;
  readonly entryPointStub: string;
}

/**
 * Scaffolds a new plugin matching docs/16-extensibility/plugin-architecture.md's
 * expected structure: a manifest plus an entry-point stub implementing
 * the minimum shape PluginManager.install expects. Returns file
 * contents rather than writing to disk — where they land is the
 * caller's concern (the desktop app or a future standalone `nova`
 * binary), consistent with this codebase's existing pattern of pure,
 * injectable classes (e.g. ObservationIndexer's ObservationMemoryWriter).
 */
export function createPluginScaffold(
  pluginId: string,
  displayName: string,
  requiredPermissions: readonly PluginPermissionScope[] = [],
): Result<PluginScaffold> {
  if (!/^[a-z0-9][a-z0-9-]{1,63}$/.test(pluginId)) {
    return err({
      code: "NOVA-CFG001",
      message: "Plugin id must be lowercase alphanumeric with hyphens, 2-64 characters.",
      retryable: false,
    });
  }
  const invalid = requiredPermissions.filter(
    (permission) => !PLUGIN_PERMISSION_SCOPES.includes(permission),
  );
  if (invalid.length > 0) {
    return err({
      code: "NOVA-CFG001",
      message: `Unknown permission scope(s): ${invalid.join(", ")}.`,
      retryable: false,
    });
  }

  const manifest: PluginManifest = {
    plugin_id: pluginId,
    version: "0.1.0",
    nova_api_version_range: "^1.0.0",
    display_name: displayName,
    description: `${displayName} — generated by \`nova plugin create\`.`,
    provided_tools: [],
    required_permissions: requiredPermissions,
    dependencies: [],
    entry_point: "index.js",
  };

  const entryPointStub = [
    "// Generated by `nova plugin create`.",
    "// docs/16-extensibility/plugin-architecture.md describes the full contract.",
    "export function start() {",
    "  // TODO: register this plugin's tools here.",
    "}",
    "",
    "export function stop() {",
    "  // TODO: release any resources acquired in start().",
    "}",
    "",
  ].join("\n");

  return ok({ manifestJson: `${JSON.stringify(manifest, null, 2)}\n`, entryPointStub });
}

export interface PluginValidationIssue {
  readonly field: string;
  readonly message: string;
}

/**
 * `nova plugin validate`: schema-shape validation plus the declared-
 * permissions check this doc calls "best-effort static check" (it
 * checks the declared scopes are real scopes, not that the plugin's
 * actual code only touches what it declares — that half requires
 * static analysis of the plugin's source, out of scope here).
 */
export function validatePluginManifest(manifest: unknown): Result<PluginManifest> {
  const issues: PluginValidationIssue[] = [];
  const record = typeof manifest === "object" && manifest !== null ? (manifest as Record<string, unknown>) : {};

  if (typeof record.plugin_id !== "string" || !/^[a-z0-9][a-z0-9-]{1,63}$/.test(record.plugin_id)) {
    issues.push({ field: "plugin_id", message: "Must be lowercase alphanumeric with hyphens." });
  }
  if (typeof record.version !== "string" || !/^\d+\.\d+\.\d+/.test(record.version)) {
    issues.push({ field: "version", message: "Must be a semver string." });
  }
  if (typeof record.nova_api_version_range !== "string" || record.nova_api_version_range.length === 0) {
    issues.push({ field: "nova_api_version_range", message: "Required." });
  }
  if (typeof record.display_name !== "string" || record.display_name.length === 0) {
    issues.push({ field: "display_name", message: "Required." });
  }
  if (typeof record.description !== "string" || record.description.length === 0) {
    issues.push({ field: "description", message: "Required." });
  }
  if (!Array.isArray(record.provided_tools)) {
    issues.push({ field: "provided_tools", message: "Must be an array." });
  }
  const requiredPermissions = record.required_permissions;
  if (!Array.isArray(requiredPermissions)) {
    issues.push({ field: "required_permissions", message: "Must be an array." });
  } else {
    const unknown = requiredPermissions.filter(
      (permission) => !PLUGIN_PERMISSION_SCOPES.includes(permission as PluginPermissionScope),
    );
    if (unknown.length > 0) {
      issues.push({
        field: "required_permissions",
        message: `Unknown permission scope(s): ${unknown.join(", ")}.`,
      });
    }
  }
  if (typeof record.entry_point !== "string" || record.entry_point.length === 0) {
    issues.push({ field: "entry_point", message: "Required." });
  }

  if (issues.length > 0) {
    return err({
      code: "NOVA-CFG001",
      message: "Plugin manifest failed validation.",
      retryable: false,
      details: { issues },
    });
  }
  return ok(manifest as PluginManifest);
}

/**
 * `nova plugin sign` (FM-12-016, supply-chain verification): signs the
 * package checksum with the maintainer's private key. Uses Node's
 * built-in RSA/EC signing (no bundled crypto dependency needed, same
 * choice as the Android companion's PairingManager) — the actual
 * archive-hashing step this checksum feeds is part of `nova plugin
 * package`, not implemented in this pass (see this file's top comment).
 */
export function signPluginChecksum(checksum: string, privateKey: KeyLike): string {
  const signer = createSign("RSA-SHA256");
  signer.update(checksum);
  signer.end();
  return signer.sign(privateKey, "base64");
}

export function verifyPluginSignature(checksum: string, signatureBase64: string, publicKey: KeyLike): boolean {
  const verifier = createVerify("RSA-SHA256");
  verifier.update(checksum);
  verifier.end();
  try {
    return verifier.verify(publicKey, signatureBase64, "base64");
  } catch {
    return false;
  }
}

export function checksumOf(data: Buffer): string {
  return `sha256:${createHash("sha256").update(data).digest("hex")}`;
}

export interface PackagedPlugin {
  readonly archive: Buffer;
  readonly checksum: string;
}

/**
 * `nova plugin package`: validates the manifest (mandatory pre-step,
 * per this file's top comment), then bundles it plus every source file
 * into a tar.gz archive (`archive.ts`) and returns its sha256 checksum
 * — the same checksum shape `signPluginChecksum` signs, so
 * `nova plugin sign` composes directly onto this function's output.
 */
export function packagePlugin(
  manifest: unknown,
  sourceFiles: readonly ArchiveEntry[],
): Result<PackagedPlugin> {
  const validated = validatePluginManifest(manifest);
  if (!validated.ok) return validated;

  const entries: ArchiveEntry[] = [
    { path: "manifest.json", content: Buffer.from(`${JSON.stringify(validated.value, null, 2)}\n`, "utf8") },
    ...sourceFiles,
  ];
  const archive = createTarGz(entries);
  const checksum = checksumOf(archive);
  return ok({ archive, checksum });
}
